version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.0.2
    ports:
      - "32000:3306"
    environment:
      
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
